version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/workspace:cached
      - $HOME/.config/gh/hosts.yml:/home/me/.config/gh/hosts.yml
      - $HOME/.config/gh/config.yml:/home/me/.config/gh/config.yml
    command: sleep infinity
